#!virtualenv/bin/python

# This script can be executed from the terminal, to start the agent, or push the current config

from sys import argv

from HAHQAgent.HAHQConfiguredAgentInstance import HAHQConfiguredAgentInstance


if __name__ == '__main__':
    try:
        agent = HAHQConfiguredAgentInstance()

        if '--push' in argv:
            agent.post_config()
        elif '--pull' in argv:
            agent.get_config()
        else:
            agent.start_agent()
    except KeyboardInterrupt:
        print 'HAProxyHQ/Agent stopped'
        exit(0)
