#!/usr/bin/env python

# this script will install requirements you'll need to run the HAProxyHQ/Agent

import os

# install virtualenv
os.system('pip install -r requirements/base.txt')

# create new virtualenv
os.system('virtualenv virtualenv')

# install requests
os.system('virtualenv/bin/pip install -r requirements/virtualenv.txt')